apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-api-key
type: Opaque
data:
  api-key: ENC[AES256_GCM,data:uw7pxyuzrTvyJLklFnWAYZloNkarXo1AmMwIzuFF7/mbtavO,iv:IM25yTHhgTpxQ1cOzJmr/YdojPCZ3KNxrY0JpCJg4j8=,tag:1k1/6n1eRcTEU/9Q7ohx6g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RnJweUU3VXNyZ08vTHor
        QUhmN1BNYjZSdzJ3RmJETTdZdjNnclNMOURBCmNWamhoTCtIUU90aTd3VTZvYzJ6
        Vmo1a3RGWEx5WEFIUzRZSHI5UGlsMzQKLS0tIDRnYTFpYW1pT21vOEpnekkxcmJ3
        TlpsSnNTT1FHV2NoMUpsU2RBVm9weXMKIGTJWeOmBitm927v5iRI0vMX7Cgqn7eR
        cB75jhoig3NEs/uRTMIKFsqRKP+vcTbNRR/TJ1Zrut8PorlFGlVV3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-21T08:33:57Z"
  mac: ENC[AES256_GCM,data:5OBvl2X84ZNwxcWi+8A8h/dbcAhKqEKj1+xGgf8K2i8P/S7rhjv5No1f83k90G1t1cqdPSgrX9r3sct9s4y0aaGo5Rm9byTAP6Vz8H7JHsrn6Ur/Cqiat/Tb2JY17KNp9hdJsAkJdEwb9cUFJF5ZipudJNNfqdshH4vzKff/Uk8=,iv:khPush3/NW0ksK4heOe4Ps7M8FR1PcuiDmxylmWLC4s=,tag:q1en+UiPzynluoN/Lvtfgw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
