apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-redis-url
type: Opaque
data:
  redis-url: ENC[AES256_GCM,data:QATJXtIHT6joQz6IS+S8NRl9BNhVqupnGomoY7DzEb1RjWBXs3yOWGeSKc2qimFlaJDwe/CeGGtwmiUDYz0dn/kzquBtyruO70+3LSTiSbrQxJElE9ZPAh5C/Wt/IMLHHHCwy5KbNJiXKJxu/E/okb6j7g/fUyJ2ENt1NQ==,iv:yBWxXfwuiAV8hPj03bxILzMB2YzKAoOFZR+CdfyjdKA=,tag:akQgEItX+nGCPd3BME5mzQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SkZtaTZvMVl6Tmx5azVv
        blNreWpwb3U1OGtvcThndVZ6K3Z4RXJhVFdFCmt2a0o2aHVwME4ya0gzdnN0eFJH
        RkxUMmpxY2dXSEZIeXFYT2FFNGtwTmcKLS0tIC9sdHN5dWw5Ri9LdG0vbFdtTG1L
        MHcwYkovWWZydkJDbk5ySkpSMDNBMzQKKColBS8TW+jAwG80FiLnYp7ucy6CCAi6
        m44t4MaprP7JnoYUDRhImnCzBDWFYDIabL2y+LfmWLEJ4RRSYSiDjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-21T08:55:45Z"
  mac: ENC[AES256_GCM,data:EXOgPIjfJwOC0v7C8SKHcu8Wyh0irCjck8G8ns6ssYQ6LACHiSL7oQd5P0YwuQrbB5inCRgy9y+rfFUCNHH6Hj+TAJwdNBOHPw/eAlscotLnw1vSva5FdPJNPLMltZVuSMQTMqBiIbxHL77wVKuRhI7T3Awda1RloBlWOCMMqeU=,iv:YISpoyjxfMchl2yoyHEj+BaPbjWsyL6iIBgBb2vTByU=,tag:YXBrwMkR5r/sSkTOyAIHPQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
