apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-redis-url
type: Opaque
data:
  redis-url: ENC[AES256_GCM,data:aw0nrUZXMFAyohT//QrbWwXtqYbU/vN21yZRBsgXcu0/kWk+ft5KTRSro8atzRpUzczhljGx/qon7KY/ArhKeNiO2gU6Emzc3BwnP5qn9YHpYcSN2FF0JcvgmoqtfGLHpQjsKUgzSjrhtDAnj1VIQSmY2Qacrw7IdWPlxQ==,iv:kTc1wKoIorgaYnoHt/UtYiR1GaQJxGxFuYVwf1ufQBo=,tag:Y83pOi1QSAQC5qTfKrC9JA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTS9UUEw1TVN3cGIvdnh1
        RVVtQ0hIOG5VWFFVdU0rcG1lbDR1VkFHZ0JjCjVpY3VjSTFROWNjQTkzd20zSUc3
        bWsyMW04bnptRW93V1F5ZDFXRVpuRFkKLS0tIDZSdTBGdks2cjNGTERqVDI4cVNY
        SzNpc1RNOWtwZmM2Y2ZoUlRkTjlXNGsKFQIok5rtYO1Lk2m2nTyZKk3pIfDJK12R
        KSAZgFHbcK+qsCaLaiJWBmjOO8DK7pQEz+g76bhBUh1peGlCFp7EWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-22T23:31:35Z"
  mac: ENC[AES256_GCM,data:lQvQlZeQ8Vxo+Deggk8g7v3IOaJ2wQozA1Yy6nVncduoYBCzATGrIN0hHMPd8CbUrBC6+9SNOGksT4fDfE2LttqVdJsBWNn251aB/nB/Bwbs2I0IS4urvHlOgsN3RJj4xOqeDZaCuYBuHpx+BCyUbwUCRMNdMisOzBNV2vRtkiU=,iv:8LMboZ8IygpcrvcohrUu/K8ILWCM9owfEIOQFGAYTFY=,tag:Ks7Mt70OeIY+lDBh8bsAfw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
