apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform
  name: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: morningnightdream/platform:latest
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
