apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app-gateway
  labels:
    app: platform-app-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-app-gateway
  template:
    metadata:
      labels:
        app: platform-app-gateway
    spec:
      initContainers:
        - name: platform-app-core-health
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', "until nc platform-app-core 8080; do echo waiting for myservice; sleep 2; done"]
      containers:
        - name: platform-app-gateway
          image: "{{ .Values.image.organization }}/platform-app-gateway:{{ .Values.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "8080"
            - name: APP_CORE_URL
              value: "http://platform-app-core:8080"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
