apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-database-url
                  key: database-url
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-api-key
                  key: api-key
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-redis-url
                  key: redis-url
            - name: FIREBASE_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secret-firebase-secret
                  key: firebase-secret
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-firebase-api-key
                  key: firebase-api-key
            - name: FIREBASE_API_ENDPOINT
              value: https://identitytoolkit.googleapis.com
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
        - name: db
          image: postgres:14.6-alpine
          env:
            - name: TZ
              value: "UTC"
            - name: LANG
              value: "ja_JP.UTF-8"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF-8"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
