apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: morningnightdream/platform:v20221223154604
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-database-url
                  key: DATABASE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-api-key
                  key: API_KEY
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
        - name: db
          image: postgres:14.6-alpine
          env:
            - name: TZ
              value: "UTC"
            - name: LANG
              value: "ja_JP.UTF-8"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF-8"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
