apiVersion: v1
kind: Secret
metadata:
  name: platform-database-url
type: Opaque
data:
  DATABASE_URL: ENC[AES256_GCM,data:+QG6C3Csiw2rSAmHwwYmNA3WTIQL0VueT0SNGWECwBYcUJGX2LRIgOPbBZXEM3CCPbQWaakW3EjZtonzPLxWjcbb1JMU4x6bmp50vn6QXNroYigf8muOYJ9xzUY9JL6Xc0P0inQ1WOpJnpe5I4KD0Jd+wuc+gDYt6p7kVV1rYdWdw3r+XvS6kzhTv0iHAN+sEEYybPl7TPLkIB+sFP7maEVk/s8+GO9Ua4lM6u+dIfRHeeVfOlgIouMYhPlPl/KBb41vmhxygQ==,iv:PZR+qpHd85oJImjmZLnkZAxnXyJJ63oyDN1s0EcCIj8=,tag:Lf5J6lum71RugrrIa3TaPA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age124g56sz2ytw6l24f0mmyvpah3g94vz7k0zjcpz76qfdf5j6e0vdsqxz2af
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSEVqSk9pbkQzWmlucGNy
        R0pLVzZad3ljME0vZnl2dVhmSk5FdkUwYTE4ClJVZTZlUS9oRmtZVXN1TGFJbjJN
        Z3JZa3pRbG9pWDRXZm1qZDBWK0h5eXcKLS0tIE9uTzVVaHhZUm5PajRCR0JNYXlr
        czR1TWd6elNINWVSZDE4MDdTWHgvNDAK26Ovng39ukXfrHpmCOYiXBw2ABNvzXCT
        GHTjaP3CdAgmHbq3AHQnD8IPReXhPyEMYy1BKKiwmcrL1VYPPGkO2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-12-10T06:50:05Z"
  mac: ENC[AES256_GCM,data:TtlvFeFBH7sUrgEtRvwZYpGiN98D44oWHDeGJZODAz097IAI+DUBeDFOT4QCHOLTYVOcjiUaoPk3Zzv6L75BwPMcnVNgtjK/yXpMG2IzPp+TgVzb5pP2i6iHbmN/zK4Q8Z94SB4zvTCjVGt56P9sOt6wZfX5QSnNFC6JopVkP84=,iv:lNKLePOdIm95ixZhH/lwcasCq6o/TaGOGP9aeJJamD0=,tag:n9zeuM6bDbXfTmu5nCtejA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
