apiVersion: v1
kind: Secret
metadata:
  name: platform-database-url
type: Opaque
data:
  DATABASE_URL: ENC[AES256_GCM,data:jm+BViDW2KnmW9xAm63MufbeJNEwINNjfKH0fFYtfooSxpj38JzUEXc+mA88cmYZedFjrX+lm9BceeiHhu3xv0G2yMDfMrARa1dKfX0yK/N6/api/akJQy/QPg==,iv:w/gkuRUN4ZHzQILPMilnM42EEPSiQUZw18Cb/O3j6vI=,tag:AD8cokJte7Bprwdl6+cxtA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age124g56sz2ytw6l24f0mmyvpah3g94vz7k0zjcpz76qfdf5j6e0vdsqxz2af
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNnBsN04vOWJkeEFYQlRK
        SWVLRXl4azRBWi9TQTZDa2ViL1hoVk1aZUdrCkRtblpnVmdNNXBDaVppcitWK3Ni
        enlvbkRIdTZ2VERGN0RhY2xIcmI1QW8KLS0tIHFqTWNCR0Nnb0xWUkNoS2E5T1RW
        QTVUK3djcStXbU95QXpaYUthdGgvTVEK8IUINCmaR6hBaAbmzduBmRLCBZ7YD/Eo
        2G0tnoyPsZrM57zboyUBfvDqmygHbERp6OVLaW1pgZCpqTu49E08ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-12-10T07:11:41Z"
  mac: ENC[AES256_GCM,data:XvmN10cq7+hzr0Z5l/jdtKfx1WdHCI7ik8tpYbax4kICj7SbYzUxOb0WbtGUOLktMju9/XxextBXV04quB1y3+UO/8Bd6E8nlJj23vF6lqLd/jDtlt6mO8ATGFoR3X8CEMUQWoryN+J/cPT5cYlNbcRcQHHx/BZPpiNXFG3uwww=,iv:FznXhVeVnOMgIbbj8Jc5xnFE6gsLFqOOWxdh3WiiKJc=,tag:Ifav13YREpC+6+pteMbdnQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
