apiVersion: v1
kind: Secret
metadata:
  name: platform-api-key
type: Opaque
data:
  API_KEY: ENC[AES256_GCM,data:xZquLFQ9q94//ZlQlDzjXzwByXZQoJ2FA4kRTgwO8WeLvN91Ttg1P5Gak5QeOsE8kDD3Dfm1jpjdG7IT/7W4vzkIWYS11Jm0PrEkL28EFMwrtz1v598BEm2aaPdAk1QjzAojI5ZCxSod5bXbzBD83UzGcB6ibywBBt+pDKeb4SSDQbMiL3PLrz93+EWiutb/oH/GiKSdCzm9UrQseq4Hh+3mUtzculJ0YPog4PT/wU2w7mv2r8boG0ApCv4PHJ9PCMDTCW/jkhCzRRvTM+Un46mOrsiehkRpePIQ9L/w8cJog+HtZfvTpUGQ7gLJX6uCGGRtFkWEhGcEhsQf5w/yCx64c3Z4qNAhHprpbOrKc2E/+M4zQTbgKVXIiEHIMkGzk+dMFfrYBxtEMneEaaonOl4EDrBr6AHnpAvNgQY7GMQDlhwbQQnjxneBMw7xy0tkfvYgYR6hmquE9iRS7+MdVPNv5YVvjMftoe4+pcIu75YK6BeCxil0u8XHGjnZnQa98x2a4vXeLcLtMgkR1CbvoZvpjOXLmPGu3q5yREzCHuVRYw9MSCGvduEBssTEblyM462uDrS29+exIO4wBcD+Xg368GjV9JfwoqzUUH461U6pTeB+7gi28te6N4kypaZnBCkwsEMi5NUMFGThMrDzhpdO1ne5dHWviK4DpMW+OredVcC0ufJXPhS7QejWBk/T9Tpc11vPoTIEu08arW87,iv:zHmD+2Vdh0vDBNjuO3oty/aiXzDzdgpT2ZZAjfH77Y0=,tag:f1lx/2AGgglDDb2zoUeTmQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age124g56sz2ytw6l24f0mmyvpah3g94vz7k0zjcpz76qfdf5j6e0vdsqxz2af
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMmdpekhsN0VCbFRiamV2
        Tnk0REZEL1hwajAvNHBLVCtnQ2xlMEdwYUhjCmh0bGZtVEo0b2RmdGJVNGllQmdC
        TDZZOHIvN2ZVV0R4dDV4MjdBRC9acEEKLS0tIHQ5WWNiK1FoeG9Nb2RKWkU3Wk1q
        d1NnSjNSL2ZhM05hMFBERHZDK0s1Qm8KbdIZRtmDHBlcdctMelm6vXtrcyt0kMfZ
        sFlRBCotNgIh0QPMBYcpVNcsB/BhiZL/kt0OwK0DoFNWQ3g9WOrWFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-12-10T06:49:50Z"
  mac: ENC[AES256_GCM,data:vZetjjX+CTlNwQByuePNPCsef7xJ0Pio/+K1Ovp8wYWLPOeHMQoz1FiH6hNedwwEirCqZS/fbVznaPWfu8vKK0bXmg4QX9tuKPwQs+m5bUA6ABwrIa33k+xWO99w6BkAT/FomRU4k1oMgpBkj6XbQ2vfrK9uA9EaAuEGZpVUC3o=,iv:ib+ssCHtgptjW27xl6DPN4DdFfCW8b+dJGPpADoGlBQ=,tag:wnvNTHv5DPMSx++Xzt5Fag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
