apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-api-key
type: Opaque
data:
  api-key: ENC[AES256_GCM,data:RUN7KTAH2R3gGx9mZMqhG0O7nKdrYojnAl3FTlh8LlYd+61yNIkAsQ==,iv:7jGx3yPn+reuikOPuRVfKstwO56Ikr5deiVU+NAcD7k=,tag:Kxfs/2vdlmFhQv1PoR56uA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SUNxbDVSS3NicERZRjBR
        VUR2N2lEUDBIRGRRcTlJS1lnR25QdEVsRkFVCmo2aXVIalAvVk1DVnV1bHpXMVd2
        OHIrOGhMN2tkM3lyRTVrd2x2eWFuLzgKLS0tIEwvRUhYRFNwM1NGUHpwdEdJTnY4
        MHYzUHdmMS94VjJQNk1ORUJyeVRSeUUKQPWtkWh2FzgOszyVJSxQKA84qb2spPrc
        CGGwd+EjwF3t5fM+bP4CR+9nqy2rv8fDzEUGLTCiGVhG96TfT3KhXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-18T06:41:28Z"
  mac: ENC[AES256_GCM,data:kRkMoYHK9Hnrmty8pV8gubBDoKYNgXIo08kHAKgEMJ7CawlxiUvkIQfDy2KJJ2soufD3QG/yIA2MUDgs+dO8ZVp4x/bR4ts0TwDE4BwH1gcqs93OZCR07HAQ3HSZY4eK1vqToKwJ+myTl38acHTPsiS2mIv5m/WH0wHYwvVpIpc=,iv:kfGTggE2Rj7e/NRNHz+ln5g40v4f6ElO8jt4/umCbo0=,tag:XfIj7VeB8oIrs7L4RnT5xA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
