apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-redis-url
type: Opaque
data:
  redis-url: ENC[AES256_GCM,data:KYQlpZ4caXE2yaBq43fzGp/6wW1DoiorLNStqSnACumfHqh9EqqAq+by81wo7Poqq5076kpa4k2UwekmJHx2L8c6Dolvs38RCSzUUkwMVAvyZjqYny0h9Snt4bBpUm2bwvpmAP5LuFo2ce/sKEhoO02Z63bigSawwJo5GQ==,iv:K6XouEWHw0DVpRC3YMYM3mz2JaggN9foHiNNUuUdjGE=,tag:MAMgP4DbicIxO98kulWdBA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRi9ScGZ3YXhYcmhkTmda
        MHJ1VXM4K0F4dDRpb2kxekw5QzZSTHN4VEd3ClVPR1ArYVpUdDUrTDJEK2RPNHlr
        Y0V6aEl1Y0U2eXhnNW83MjhsRUVBbUUKLS0tIFhiY2txL1ovSVdkQ1dQcjg1dUE1
        UDlEcUx2QldJVHFWcUYvN3JaaDUzYVUKqPd73a1ObddTpcJA3pdJBFB0PLrPdFPx
        9Cg99RWuGFmj2ZSg4ARPq4Nyl1wr8NpubgkSBMenqxZA3RkoYYWe7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-15T15:29:16Z"
  mac: ENC[AES256_GCM,data:bJaGIIg+Eo7VvUGz6Am7kaI1HzPDhomaTZGUbIIUIfCFl9a4y+riyk6IV++fpKTRk+ayVTLXgold/qlSMttxnrq0bAzXUKjDX3+PblF2biLPAPDMZomyS3Mnw0idm31MF3vFd2B3NA8MwAOv8/fDZkSn9TSw+JmNC58TFqnEQ8s=,iv:gSvhSNOsR2naKBueUOISbXqOps3VlGoThE+hdVZMJQ0=,tag:SYuciW2/cBgV+llsGRaiqA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
