apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-redis-url
type: Opaque
data:
  redis-url: ENC[AES256_GCM,data:OhZkbVcT58O/eoOjGsVpg+zaFgujIThF454whhViQLZSacoXQ2wLTcL1IaSSrgfnnXjJDzalbUsUnDMTgxWcLNKxsKNcvYwrhe6s2LVlHsryfuzuWhg3D0gqUYP25s5RTnl2PuYeZIdenwwNa7T68B/vqYVyuLK4Xs/oGw==,iv:fqZ5tu6cHeMyMpdTh5o9WXR3hoOM0FX9mSc7Z9gqQ0A=,tag:kbOwfseZjggE+aklsOSr2w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVWxBNzZRWllLWHhKemdY
        QVVNNzMvdmdWM2pmUldnWFZzem1YMmRCenpRCmxvOU1PS3o5MzBjclJRa2dHL1Ns
        ZTBrZ1FGZUowQmFlaW5vQmdMU2dtekEKLS0tIFlYaDlncjhVZ3MvWnlZWGR5ZkdF
        S1dXYStSdnJHZHh6UEFjWVdGbTAyV2cKTVgE2vnGZyA4iDD/laa+lwPALkuMyktU
        u5J5wSpFrWoSxK4pQ4xwH5G5iWvtHf39mqZwVFplFAtGZp8NhtaPUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-12T15:09:05Z"
  mac: ENC[AES256_GCM,data:urLSVMWasm1s3komy9HsrJVxltn+CMJee6cZ23Jj1KiVzx9cOoJMPhXlXweVVs4LJgt7hbIlKxEhSE6Kp4o7ilAFizQ+vzw5DMlnE8Jfk4m+98yjH4AvigJdrTsQXUefmXz0a36hoCb70Ty5gcnPpp11q8SxwPdte1IKVSoSlu0=,iv:Jrj2kqC6agfLLXTa8jH48oONZmHecquYryTgs+unR7M=,tag:l62SWJ94WHI0aIulJlmiKA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
