apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-app-api-domain
type: Opaque
data:
  app-api-domain: ENC[AES256_GCM,data:ntwvu96ughOk98wUiyhjyGMGzR+EHHNUMrk9mHU/0UbDMWAN1MYZVIIHrsqMUlk3hxyf/UiDlRrJnkZH7Qpi4Td9dLcWOUGaWM2RNlN0EAo=,iv:c3/Sd3TgvUlp6ruqfo05NrlOn+SA3Hvt+cIgZCi/oGE=,tag:9rrA8oDxRCxm5gaKwZIqEw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNFZnV2oydldxRzZWQ2F5
        dHEwS2lBSGtiQldUUERMZUF0VE03YWlPdFM4CmZNQ1g1V3FoN3JPamRGdlFtS2tY
        OEgzbE9abEdGWW81ajlYcGhoKzlid1kKLS0tIGZ1M0I5VnFtbW1aZ0U1UnlvSGdV
        aW1UTFNWa0V1bzRJNGhMaFhEbGQxRUkK74Y8/RpYnUBwZyM0Vp4+5zCzSWwuZ32Z
        fzYeNeoVBIzhufLFhbhLN4vYj7tyOPAbr2nPjwT5cQdjkeFZ+FTObQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-25T07:00:22Z"
  mac: ENC[AES256_GCM,data:a/zV8of0q2bjKw3Jo/CXirXkokow3uaH8ZONE4hpWzOEYDoFhGZFXHH1so1EWUI1QnX1cWrLmDTkrFb7fHCsswTq60g+QStIOXdquQjJWBbAl0KADpupCoOgZSYnW3LIiR8b98khMS+5VPv9wHo6zgNYoC5sp9J3sysL0JVMl0s=,iv:FyCt9XT/zpJ/6MxCVacOroPHaP/IVnSL6Yd2hn63gUs=,tag:2YcjB28eHid/T5QPgUGU9w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
