apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-firebase-api-key
type: Opaque
data:
  firebase-api-key: ENC[AES256_GCM,data:lG/0qQThbVzAosHsQbwtizmjd3dD5ci0rFkaOJVJ1stuKKEGqifN6OJLSqY6sefHiCE+TA==,iv:lxK228hnshrlsUh0oA33iRcz03vH2doBk7hEFR/8QFY=,tag:Zl/elzYimGK4r+8m+E0kZA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3anB5eEY3a21tTkNyMkJO
        bnVMVitWVlNCTHY4b3c4QVVVMTR1WFJhZ1NVCm1SeTRSeG9PSXNFYWxDK2hnRng4
        Q2hFbGJWZXoyVmlZM2RSQ2JnaUo3YzgKLS0tIFBGRFh0WkRxa05wVFpEQzNlQVRS
        dWJLcVdPU2Vma2NFb3dmWXNQQkNldkUKnmauTrXOb9oRkwK4CnneVkkOEg0ikfa5
        IVHD+eBZXs5eNxavgpu4tRwqEf8Ri25F9T565uR5QBDG89gvgXKnqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-28T06:02:12Z"
  mac: ENC[AES256_GCM,data:9q0QoT7AIyilTjEhKj+ivCqWU/jyiSVXCj/V20CkUar/fFkFN3W4Fh2ks/tJtLrB10wT76UajuKwRzHFPd+NUb3Z39tR2MmvnJyWnvA19yykoRUZRfsjbMMkdl9M9fkewp2K+6d6rErWRwS07e2MgsnznrOFSTPCTzQvPJSS8tQ=,iv:cq7takxi+KuJ26G6LRON3IjsOfi0C0N2L/HPgmVmTrE=,tag:xbQGRl3PAELVUtmKmGzHDg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
