apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-upstash-redis-url
type: Opaque
data:
  upstash-redis-url: ENC[AES256_GCM,data:HAs2myRPC3HrPEfJ+L9fwf0KaBENnh1NKinzBMMYWl6Zxaecc0jmWXkSMHTqhD6uJJnqe1B8dO4a4Jwe0KkaQSAsImoORW21Iruk8nEdvc7+Y7TiveX5xuf7f9jG5t9nenoC7vDagER/Kn6NlyJvnIznuc1E2Zy4FfMv7A==,iv:GaXch9gL4O9EuEsUQxwi5RXeXfLQT1TG+HheL4MNeck=,tag:0fqb0BlqZ1pdDaTtLreeig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aWpaRU93N1ljamNxVFVp
        UTU5Yzd0dE53QXdJYkpoTGRTQVppd2NubGcwCjhkMG5lVXhwNE1PUGlXbzJFdXI1
        TlBUU2RSWTFzekgvKzZ0eUxrbCtsSEkKLS0tIE9aSlJaWFErcDczaVdyYWNjVE1q
        K3B2MUE1eGRvR3I5QlY2MFJETFVEcTAKREigU9BEDl2TWZYz7/CUDVoTDAmeC3d5
        WLyShKbxKcvt+DLE4GVhX7GRwy2vLUMPWMxQcoaCWzJWD7TnJ7ZutA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-18T11:37:30Z"
  mac: ENC[AES256_GCM,data:ZzSG62Ph31SewqjJmsjI+Yi+gdzd02ZCnAs3CnKv98TB/hjKBVYMmfkuXgTprksgW9e0Oa3E/aG+odVmuCYCjCdhEYNGrnSzh09WsRCF/mXloazpIlcfVftryd+vnMWjrB9M9SRZVoUaM7At3FJ+dbU6vFJB9MwBrLDHe+qIY2w=,iv:et1I5+Ii1+3q213UP5rFJH3N6/sB7ORhALEIAiov+5I=,tag:p8XETrwxN6ObNilP6mmwIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
