apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-yogabyte-db-url
type: Opaque
data:
  yogabyte-db-url: ENC[AES256_GCM,data:L5xZ0ol3X/aukUpK80C0dYspAPjoxQHMRhEKWJKjuApTGyFecZG3adamX9xgbGljRCYe8i4KA1VChskw23mskYyIOvSbKNRyp9/TAkzwRt1hXKNyUATH0AqsSCc0xTCtftm1+YL47/z1VrupEM+BuHBSq/S6GwhvdPApSmzstJ/wJW128u9EoSVktmPwAaSSlnhtxJY7PqMD37OzeABRI8eUSH9eRP3kG8Nnqq5k5pMEzGxcR46y1My8X0hebZXHI6zNbA==,iv:qyCwF+kEd4lnwAOHdUP7nOZwYQ58W9xpJ+VSEnzVGfQ=,tag:Zu2pSixtH60fQo/9gWU/TA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQThZOTV5Z1JFbXBKWFd2
        bDQxam1BWXNoUmNFK0tGb0N0WVhJazlVOUNFCkFWa1dpMzZDUHRGSFlJRUVJZ3Vl
        RFYyWEl5MTJSampqam1TTUdpaXlhRVUKLS0tIDlCK2N0ODdwVFpnL2lHQXdDMDQ1
        amJnaS9BR2lhNVhIaW4yb3RRdFQvK2sKy99koDVD+oxPdcvorcX6cVL34GcAKwgv
        WCOdpHm7qW97ZJM9dgZhKIGuov9nymleu+1+AlhAO6vf3Ed+aGnUIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-18T11:35:57Z"
  mac: ENC[AES256_GCM,data:ULmYJyL5fWduyMWbkinwxQjz/WXVA9FnxpQdJdyIc+eYbfgSXRBZmB7rbJOnh/VGBsaoPy4uBR5DWig2IYyCmYuZTjNvfWk2G+iEGC6fe+jXiIPsHzPPku4hWQKltpmVFqknoXQomcy8BLp36RpOs9hDAZ4SpgD+IgNHS+eXPJc=,iv:UE5/PLbeHvjKlZP8M8zxPW73zemVsYm8oz5QYQM33yM=,tag:12Z84wmakh7uueYBs93w1A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
