apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-yugabyte-db-url
type: Opaque
data:
  yugabyte-db-url: ENC[AES256_GCM,data:MBaclO2r/cEnYZFPc6kuvl2VBmH2KImsh+vDybO7y42tIv0jlmvenHzPP+InRKIToudswPyRrCoLguy25a94u8u5mVdPiXV7SS57r1jaf0AsnJkxN1fzGnxPP+7LpD4FtUNmoIhapXY3qXUkaLyzCWHaZIseaRcYGxsbUFHdKW8jj8iVarYQRVl6WdtHoziQEupZF0aotVEMEe1hlAmIs9qNB0ySd1oxUzRA40Jco5zDzNhBFQ7gOo6tavGgsKkd38zd9cbr2MFzDKeJCOcrRLeNo1nSZvd9SiHe4NBKT6JJ0tkfI/b56MBxGX3YKxkvM2RLMjk1XOG5TXH3CezMM8c4i2MdsMf8IJ5Ubg==,iv:nZEfXpLc7IkLleQKuA3N9QYitLvCtSNP9nkK1JkIiog=,tag:oaVkwn3xRI2wBsr7Yz2G4w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN3M0LzliNWF2YTNETFA1
        S0xma09ndjlNYktoV2lBT1h2OEdBTGpoOURNCnNKWmtyZm54cFV1UFIvS2MxUEVT
        a0ovbFdJSUNUVE5hWmljWGJjVElCOU0KLS0tIGQybXc3MWFGV1RCUXFCcTRPRFRI
        MnBXdjZyUW9OcHI0NmFRcnNBZ2lmYTAKXiVbuqBxwzRvigGkEQJdCVlM04KAnbtc
        AaSRQB/noQ6EBrSwigSUie7KLzglFFRdt9GMr8f5BJFlUlDZOiBNIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-18T13:09:20Z"
  mac: ENC[AES256_GCM,data:3nSVblAO0GemBeb2JVhdGTSAphcPyLeL4suh65QP4YAKYHpqGktAWm5CfBSNgV2uywgjbu6cI9QfGRKyL7QSLni3o+flV8p1554ukJ2f62/5bLeX6C7p0zwVLqfVqWFUr14yrzqclVIWbBf19ZUNw5Sky8hvT0ICugSjbzpWRSw=,iv:RIIYPsB56hFQDuhP+Q1hMW3fy4ZWr1WkquFd2oyylqU=,tag:L/va4D13D5eIDht0TCT9SA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
