apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app-core
  labels:
    app: platform-app-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-app-core
  template:
    metadata:
      labels:
        app: platform-app-core
    spec:
      containers:
        - name: platform-app-core
          image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-database-url
                  key: database-url
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-api-key
                  key: api-key
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-redis-url
                  key: redis-url
            - name: FIREBASE_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secret-firebase-secret
                  key: firebase-secret
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-firebase-api-key
                  key: firebase-api-key
            - name: FIREBASE_API_ENDPOINT
              value: https://identitytoolkit.googleapis.com
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
