apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app-api
  labels:
    app: platform-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-app-api
  template:
    metadata:
      labels:
        app: platform-app-api
    spec:
      initContainers:
        - name: platform-app-core-health
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', "until nc platform-app-core 8080; do echo waiting for platform-app-core; sleep 2; done; echo healthy platform-app-core"]
      containers:
        - name: platform-app-api
          image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "8080"
            - name: APP_CORE_URL
              value: "http://platform-app-core:8080"
            - name: FIREBASE_SECRET
              value: '{"type": "service_account","project_id": "emulator"}'
            - name: FIREBASE_API_ENDPOINT
              value: http://localhost:9099/identitytoolkit.googleapis.com
            - name: FIREBASE_API_KEY
              value: emulator
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-redis-url
                  key: redis-url
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
