name: manifest find
on:
  push:
    paths:
      - .github/workflows/manifest.find.yaml
jobs:
  find:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find chart
        run: |
          for chart in $(find charts -mindepth 1 -maxdepth 1 -type d) ; do
            echo "${chart}";
          done
