name: okteto
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'
jobs:
  okteto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install okteto
        run: curl https://get.okteto.com -sSfL | sh
      - name: Okteto login
        run: okteto login --token ${{ secrets.OKTETO_TOKEN }}
      - name: Okteto namespace
        run: okteto namespace use fs-morning-night-dreamer
      - name: Okteto deploy
        run: okteto deploy
