name: terraform plan
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/terraform.plan.yaml
      - '**.tf'
      - '**.hcl'
      - '**.template'
env:
  COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}
  TF_VAR_yugabyte_auth_token: ${{ secrets.YUGABYTE_AUTH_TOKEN }}
  TF_VAR_password: ${{ secrets.PASSWORD }}
  TF_VAR_upstash_email: ${{ secrets.UPSTASH_EMAIL }}
  TF_VAR_upstash_api_key: ${{ secrets.UPSTASH_API_KEY }}
jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
